- id: 1
  pos:
    x: 0.78
    y: -1.32
  rot:
    theta: -1.57
- id: 2
  pos:
    x: -0.32
    y: -1.07
  rot:
    theta: 3.14
- id: 3
  pos:
    x: -0.32
    y: 0.10
  rot:
    theta: 3.14
- id: 4
  pos:
    x: -0.32
    y: 0.79
  rot:
    theta: 3.14
- id: 5
  pos:
    x: 0.97
    y: 1.18
  rot:
    theta: 1.57
- id: 6
  pos:
    x: 1.91
    y: 1.18
  rot:
    theta: 1.57
- id: 7
  pos:
    x: 2.18
    y: -0.29
  rot:
    theta: 0.0
- id: 8
  pos:
    x: 1.92
    y: -1.32
  rot:
    theta: -1.57
- id: 9
  pos:
    x: 0.57
    y: 0.29
  rot:
    theta: 1.57
- id: 10
  pos:
    x: 0.61
    y: -0.68
  rot:
    theta: 3.14
- id: 11
  pos:
    x: 1.28
    y: -0.39
  rot:
    theta: -1.57
- id: 12
  pos:
    x: 0.51
    y: -0.26
  rot:
    theta: -1.57
- id: 13
  pos:
    x: 1.61
    y: 0.24
  rot:
    theta: 1.57