- id: 13
  pos:
    x: 1.449
    #x: 1.549
    y: -0.145
  rot:
    theta: 0
- id: 11
  pos:
    x: -0.296
    #x: -0.296
    #y: -0.981
    y: -0.981
    #y: -1.081
  rot:
    theta: 3.14
- id: 10
  pos:
    x:  1.75
    y: -2.095
  rot:
    theta: -1.57
- id: 8
  pos:
    x:  1.8076
    y: -0.1661
  rot:
    theta: 1.57
- id: 3
  pos:
    x: -0.0751
    y: -2.0926
  rot:
    theta: -1.57
- id: 12
  pos:
    x:  2.0769
    y: -1.0217 
  rot:
    theta: 0
- id: 2
  pos:
    x:  0.7339
    y: -2.0961 
  rot:
    theta: -1.57
